# src/main/resources/application.properties
spring.application.name=digital-banking-system-backend

# Server
server.port=8085

# Datasource (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ebank_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# H2 (uncomment to use in-memory DB for development)
# spring.datasource.url=jdbc:h2:mem:db
# spring.h2.console.enabled=true
# spring.datasource.driver-class-name=org.h2.Driver

jwt.secret = "ZvqMZiz5kAlnR3ClYHqa4zsnKrcaq32Fq1FB1NeLb5rNtWpB1x/bVyJPRf3Sf4QXpdtWAN9s0Tbn+whxBxjKg=="
